<?php

namespace Modules\Lesson\Http\Controllers;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Modules\Classes\Models\SchoolClass;
use Modules\Lesson\Models\LessonReport;
use Modules\Lesson\Services\LessonReportPdfService;
use Modules\Lesson\Services\LessonReportService;
use Modules\Student\Models\StudentDetails;

class LessonReportController extends Controller
{
    /**
     * Display a listing of the resource: pick a class, see its daily and
     * weekly lesson attendance reports.
     */
    public function index(Request $request)
    {
        abort_unless(Auth::user()->can('view lesson'), 403);

        $classes = $this->scopedClasses();

        $selectedClass = null;
        $classId = $request->integer('class_id') ?: $classes->first()?->id;
        if ($classId) {
            $selectedClass = $classes->firstWhere('id', $classId);
        }

        $reports = collect();
        if ($selectedClass) {
            $reports = LessonReport::where('class_id', $selectedClass->id)
                ->orderByDesc('period_start')
                ->limit(30)
                ->get();
        }

        return view('lesson::reports.index', compact('classes', 'selectedClass', 'reports'));
    }

    /**
     * Show the specified resource, including a fresh day-by-day breakdown
     * (not just the stored totals) so corrections since generation show up.
     */
    public function show(int $id, LessonReportService $reportService)
    {
        abort_unless(Auth::user()->can('view lesson'), 403);

        $report = $this->scopedReport($id, ['schoolClass', 'generatedBy']);
        $days = $reportService->compute($report->schoolClass, $report->period_start, $report->period_end)['days'];

        return view('lesson::reports.show', compact('report', 'days'));
    }

    /**
     * Compute (or recompute) a class's daily or weekly report on demand,
     * rather than waiting for the nightly/weekly schedule.
     */
    public function generate(Request $request, LessonReportService $reportService)
    {
        abort_unless(Auth::user()->can('export lesson'), 403);

        $validated = $request->validate([
            'class_id' => 'required|exists:classes,id',
            'type' => 'required|in:daily,weekly',
            'date' => 'required|date',
        ]);

        $class = $this->scopedClasses()->firstWhere('id', $validated['class_id']);
        abort_unless($class, 403);

        $date = Carbon::parse($validated['date']);

        if ($validated['type'] === 'daily') {
            $start = $date->copy();
            $end = $date->copy();
        } else {
            $start = $date->copy()->startOfWeek(Carbon::MONDAY);
            $end = $start->copy()->addDays(4);
        }

        $stats = $reportService->compute($class, $start->copy(), $end->copy());

        $report = LessonReport::updateOrCreate(
            ['class_id' => $class->id, 'type' => $validated['type'], 'period_start' => $start->toDateString()],
            [
                'institution_id' => $class->institution_id,
                'period_end' => $end->toDateString(),
                'total_lessons' => $stats['total'],
                'attended_count' => $stats['attended'],
                'not_attended_count' => $stats['notAttended'],
                'recovered_count' => $stats['recovered'],
                'generated_by' => Auth::id(),
                'generated_at' => now(),
            ]
        );

        return redirect()->route('lesson.reports.show', $report->id)->with('success', 'Report generated.');
    }

    /**
     * Download the report as a PDF, generating it first if it doesn't
     * already exist (weekly reports are auto-generated by the schedule;
     * daily reports are only rendered to PDF on first download).
     */
    public function download(int $id, LessonReportPdfService $pdfService)
    {
        abort_unless(Auth::user()->can('view lesson'), 403);

        $report = $this->scopedReport($id, ['schoolClass']);

        if (! $report->pdf_path || ! Storage::disk('public')->exists($report->pdf_path)) {
            $pdfService->generate($report);
        }

        $filename = sprintf(
            '%s-%s-%s.pdf',
            str($report->schoolClass->name)->slug(),
            $report->type,
            $report->period_start->format('Y-m-d')
        );

        return Storage::disk('public')->download($report->pdf_path, $filename);
    }

    private function scopeToViewer($query): void
    {
        $user = Auth::user();

        if (isAdmin()) {
            return;
        }

        if ($user->hasRole('Teacher')) {
            $institutionId = $user->teacherUserDetails?->institution_id;
            $query->where('institution_id', $institutionId ?? 0);

            return;
        }

        if ($user->hasAnyRole(['Parent', 'Student'])) {
            $institutionIds = $user->hasRole('Parent')
                ? StudentDetails::where('parent_id', $user->id)->pluck('institution_id')
                : StudentDetails::where('student_id', $user->id)->pluck('institution_id');

            $query->whereIn('institution_id', $institutionIds);

            return;
        }

        $query->whereIn('institution_id', $user->institution()->pluck('id'));
    }

    private function scopedReport(int $id, array $with = []): LessonReport
    {
        $query = LessonReport::with($with);
        $this->scopeToViewer($query);

        return $query->findOrFail($id);
    }

    /**
     * Classes selectable for lesson reports, scoped to the viewer's own
     * class(es)/institution unless they're an Admin.
     */
    private function scopedClasses()
    {
        $user = Auth::user();

        if ($user->hasRole('Parent')) {
            $classIds = StudentDetails::where('parent_id', $user->id)
                ->pluck('class_id')->filter()->map(fn ($id) => (int) $id)->unique();

            return SchoolClass::whereIn('id', $classIds)->orderBy('name')->get();
        }

        if ($user->hasRole('Student')) {
            $classId = StudentDetails::where('student_id', $user->id)->value('class_id');

            return SchoolClass::whereIn('id', array_filter([(int) $classId]))->orderBy('name')->get();
        }

        if ($user->hasRole('Teacher')) {
            $institutionId = $user->teacherUserDetails?->institution_id;

            return SchoolClass::where('institution_id', $institutionId ?? 0)->orderBy('name')->get();
        }

        $query = SchoolClass::query();

        if (! isAdmin()) {
            $query->whereIn('institution_id', $user->institution()->pluck('id'));
        }

        return $query->orderBy('name')->get();
    }
}
